# Laboratorium 4 — NumPy zaawansowane
**Autor:** [ Paweł Winnik]

In [52]:
import numpy as np

In [53]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


## Zad 1a

In [54]:
piec_procent = ceny * 1.05
print(piec_procent)

[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


## Zad 1b

In [55]:
rabaty = np.array([0.10, 0.05, 0.15])
po_rabatach = ceny * (1 - rabaty)
print(po_rabatach)


[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


## Zad 1c

In [56]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
koszt_zakupu = ceny / (1 + marza)
print (koszt_zakupu)

[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


## Zad 1d


In [57]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99], # Produkt A
[49.99, 52.99, 47.99], # Produkt B
[14.99, 15.99, 13.99], # Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
id_min = ceny.argmin(axis = 1)
for i in range(4):
    print(f"Produkt {produkty[i]} jest najtańszy w {sklepy[id_min[i]]}")

Produkt A jest najtańszy w Online
Produkt B jest najtańszy w Online
Produkt C jest najtańszy w Online
Produkt D jest najtańszy w Online


## Zad 2a

In [58]:
# Dane miesięczne z jednego roku (flat)
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


# Zad 2b

In [88]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


## Zad 2c

In [89]:
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
macierz = sprzedaz_flat.reshape(6, 2)
print(macierz)
srednia_sprzedaz = macierz.mean(axis=1)
print(srednia_sprzedaz)
zmiana = macierz[:, 1] - macierz[:, 0]
print(zmiana)

[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
[150. 225. 215. 170. 240. 225.]
[100 150 -70 100 140 -70]


## Zad 2d

In [90]:
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
# Przekształć na kwartały (4 kwartały × 3 miesiące)
kwartaly = dane_flat.reshape(4, 3)
print(kwartaly)
kwartaly.flatten()
np.concatenate([dane_flat, np.array([235])])

[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]


array([120, 135,  98, 142, 167, 189, 201, 178, 156, 143, 198, 221, 235])

## Zad 3a

In [91]:
#Dane
np.random.seed(2026)
# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

In [92]:
#1
srednia_pensji = pensje.mean()
mediana_pensji = np.median(pensje)
odchylenie_s_pensji = pensje.std()
print(srednia_pensji, mediana_pensji, odchylenie_s_pensji)
#2
nazwy = np.array(pracownicy)
print(nazwy[pensje > srednia_pensji])
#3
print(nazwy[pensje < mediana_pensji])
#4
IQR = np.percentile(pensje, 75) - np.percentile(pensje, 25)
print(IQR)

6425.0 6050.0 1616.9029037020127
['Jan' 'Marek' 'Zofia']
['Anna' 'Ewa' 'Piotr' 'Tomek']
2200.0


## Zad 3b

In [93]:
# Zasady premii:
# - ocena >= 4.5 → premia 2000 zł
# - ocena >= 4.0 → premia 1000 zł
# - ocena < 4.0 → premia 0 zł
premie = np.where(oceny >= 4.5, 2000,
np.where(oceny >= 4.0, 1000, 0))
nowe_wynagrodzenie = pensje + premie
print("Premie:", premie)
print("Nowe pensje:", nowe_wynagrodzenie)
najwyzsza_premia = np.argmax(premie)
print(f"Najwyższą premię dostała {nazwy[najwyzsza_premia]}, kwota to: {premie[najwyzsza_premia]} zł.")

Premie: [1000    0 2000 1000 2000    0 1000    0]
Nowe pensje: [ 6500  7200  6800 10100  8300  4200  9500  5800]
Najwyższą premię dostała Ewa, kwota to: 2000 zł.


## Zad 3c

In [94]:
kolejnosc = np.argsort(pensje)[::-1]
for i, idx in enumerate(kolejnosc, 1):
    print(f"{i}. {nazwy[idx]} - Pensja: {pensje[idx]} zł")

1. Marek - Pensja: 9100 zł
2. Zofia - Pensja: 8500 zł
3. Jan - Pensja: 7200 zł
4. Kasia - Pensja: 6300 zł
5. Tomek - Pensja: 5800 zł
6. Anna - Pensja: 5500 zł
7. Ewa - Pensja: 4800 zł
8. Piotr - Pensja: 4200 zł


## Zad 3d

In [95]:
print(np.corrcoef(staz, pensje)[0, 1])
print(np.corrcoef(staz, oceny)[0, 1])

0.987862864584301
0.04198471605953068


## Zad 3e

In [96]:
ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol
print(f"Macierz przychodu: {przychod}")

Macierz przychodu: [[ 73500 539000 161000 339500 339500 171500]
 [244800 316800 358200  86400 270000  84600]
 [ 67500 290000 387500 327500 420000 452500]
 [ 10200   8700   6750  13200  19800  12000]]


## Zad 4

In [107]:
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)
print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}")
print(np.corrcoef(wiek, wydatki)[0, 1])
def pokaz_statystyki(nazwa, dane):
    print(f"{nazwa:10} | Średnia: {dane.mean():.1f} | Mediana: {np.median(dane):.1f} | "
          f"Std: {dane.std():.1f} | Min: {dane.min()} | Max: {dane.max():.1f}")
pokaz_statystyki("Wiek", wiek)
pokaz_statystyki("Wydatki", wydatki)
pokaz_statystyki("Wizyty", wizyty)
kor_wiek_wydatki = np.corrcoef(wiek, wydatki)[0, 1]
kor_wizyty_wydatki = np.corrcoef(wizyty, wydatki)[0, 1]
print(f"Korelacja Wiek vs Wydatki: {kor_wiek_wydatki:.3f}")
print(f"Korelacja Wizyty vs Wydatki: {kor_wizyty_wydatki:.3f}")
sr = wydatki.mean()
sd = wydatki.std()
segmenty = np.where(wydatki > sr + sd, 'WYSOKI', 
           np.where(wydatki < sr - sd, 'NISKI', 'ŚREDNI'))
nazwy_segmentow, liczebnosc = np.unique(segmenty, return_counts=True)
print("\n--- 5. PODSUMOWANIE SEGMENTÓW ---")
for nazwa, ile in zip(nazwy_segmentow, liczebnosc):
    procent = (ile / len(segmenty)) * 100
    print(f"Segment {nazwa:7}: {ile:2} klientów ({procent:.1f}%)")

Wiek — średnia: 34.2, mediana: 33.5
-0.08502552221509482
Wiek       | Średnia: 34.2 | Mediana: 33.5 | Std: 9.2 | Min: 18 | Max: 59.0
Wydatki    | Średnia: 505.6 | Mediana: 508.7 | Std: 197.6 | Min: 0.0 | Max: 915.3
Wizyty     | Średnia: 4.8 | Mediana: 5.0 | Std: 2.0 | Min: 1 | Max: 9.0
Korelacja Wiek vs Wydatki: -0.085
Korelacja Wizyty vs Wydatki: 0.037

--- 5. PODSUMOWANIE SEGMENTÓW ---
Segment NISKI  : 17 klientów (17.0%)
Segment WYSOKI : 17 klientów (17.0%)
Segment ŚREDNI : 66 klientów (66.0%)
