# Laboratorium 3 - NumPy
**Autor:** [Paweł]

In [73]:
import numpy as np

# 1. Z listy

In [74]:
oceny = np.array([4.0, 3.5, 5.0, 4.5, 3.0, 4.0, 5.0])
print(f"Oceny: {oceny}")
print(f"Typ: {oceny.dtype}")

Oceny: [4.  3.5 5.  4.5 3.  4.  5. ]
Typ: float64


# 2. Zera - 10 elementów

In [75]:
zera = np.zeros(10)
print(f"Zera: {zera}")

Zera: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 3. Jedynki - macierz 3*5

In [76]:
jedynki = np.ones((3, 5))
print(f"Jedynki:\n{jedynki}")

Jedynki:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 4. Sekwencja od 0 do 100, co 10

In [77]:
dziesiatki = np.arange(0, 101, 10)
print(f"Dziesiątki: {dziesiatki}")

Dziesiątki: [  0  10  20  30  40  50  60  70  80  90 100]


# 5. 7 równomiernych punktów od 0 do 1

In [78]:
ulamki = np.linspace(0, 1, 7)
print(f"Ulamki: {ulamki}")

Ulamki: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


# 6. 20 losowych ocen od 2 do 5

In [79]:
np.random.seed(42)
losowe_oceny = np.random.randint(2, 6, size=20)
print(f"Losowe oceny: {losowe_oceny}")

Losowe oceny: [4 5 2 4 4 5 2 2 4 3 4 4 4 4 5 2 5 5 5 4]


# Zbadaj tablicę losowych ocen

In [80]:
print(f"shape: {losowe_oceny.shape}")
print(f"ndim: {losowe_oceny.ndim}")
print(f"size: {losowe_oceny.size}")
print(f"dtype: {losowe_oceny.dtype}")

shape: (20,)
ndim: 1
size: 20
dtype: int32


In [81]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
print(miesiace_sprzedaz[0])
                             

120


In [82]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
print(miesiace_sprzedaz[-1])

221


In [83]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
print(miesiace_sprzedaz[0:3])

[120 135  98]


In [84]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
print(miesiace_sprzedaz[-3:])

[143 198 221]


In [85]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
print(miesiace_sprzedaz[0:11:2])

[120  98 167 201 156 198]


In [86]:
miesiace_sprzedaz = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
print(miesiace_sprzedaz[::-1])

[221 198 143 156 178 201 189 167 142  98 135 120]


# Sprzedaż 4 produktów w 3 kwartałach

In [87]:
# 1. Sprzedaż Produktu A w Q2 (wiersz 0, kolumna 1):
dane = np.array([
[120, 145, 167], 
[89, 102, 95], 
[234, 267, 289],
[56, 78, 91]])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']
wynik = dane[0, 1]
print(wynik)

145


In [88]:
# 2. Cała sprzedaż Produktu C (wiersz 2, wszystkie kolumny)
dane = np.array([
[120, 145, 167], 
[89, 102, 95], 
[234, 267, 289],
[56, 78, 91]])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']
wynik = dane[2, :]
print(wynik)

[234 267 289]


In [89]:
# 3. Sprzedaż wszystkich produktów w Q1 (wszystkie wiersze, kolumna 0):
dane = np.array([
[120, 145, 167], 
[89, 102, 95], 
[234, 267, 289],
[56, 78, 91]])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']
wynik = dane[:, 0]
print(wynik)

[120  89 234  56]


In [90]:
# 4. Sprzedaż Produktów B i C w Q2 i Q3 (wiersze 1-2, kolumny 1-2):
dane = np.array([
[120, 145, 167], 
[89, 102, 95], 
[234, 267, 289],
[56, 78, 91]])
produkty = ['Produkt A', 'Produkt B', 'Produkt C', 'Produkt D']
kwartaly = ['Q1', 'Q2', 'Q3']
wynik = dane[1:3, 1:3]
print(wynik)

[[102  95]
 [267 289]]


In [101]:
#  Produkty w sklepie internetowym
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])

In [112]:
#Zad 1
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])
print(f"Średnia cena produktów: {ceny.mean()}")
print(f"Najdroższy produkt kosztuje: {ceny.max()} złotych i jest to {nazwy[ceny.argmax()]}.")
print(f"Najtańszy produkt kosztuje: {ceny.min()} złotych i jest to {nazwy[ceny.argmin()]}.")


Średnia cena produktów: 1171.0
Najdroższy produkt kosztuje: 3499 złotych i jest to Laptop.
Najtańszy produkt kosztuje: 89 złotych i jest to Ładowarka.


In [117]:
#Zad 2
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])
wartosc_produktow = ceny * ilosci_magazyn
print(wartosc_produktow)
wartosc_magazynu = np.sum(wartosc_produktow)
print(f"Łączna wartość magazynu to: {wartosc_magazynu}")

[ 52485  79758 194922  54444  27768  22161  25929  34477  26955  30566]
Łączna wartość magazynu to: 549465


In [123]:
#Zad 3
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])
promocja_swiateczna = ceny * 0.85
print(f"Ceny po rabacie 15%: {promocja_swiateczna}")
ceny_vat = ceny + ceny * 0.23
print(f"Ceny po VACIE 23%: {ceny_vat}")
warunek = ceny > 1000
print((warunek).sum())

Ceny po rabacie 15%: [2974.15 1614.15 2124.15  296.65   75.65  211.65  109.65 1274.15  509.15
  764.15]
Ceny po VACIE 23%: [4303.77 2335.77 3073.77  429.27  109.47  306.27  158.67 1843.77  736.77
 1105.77]
4


In [128]:
#Zad 4
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])
warunek_ocen = oceny_klientow >= 4.5
wybrane_nazwy = np.array(nazwy)[warunek_ocen]
wybrane_ceny = ceny[warunek_ocen]
print(f"Produkty z oceną 4.5 to {wybrane_nazwy} a ich ceny to kolejno: {wybrane_ceny}")
ponizej_dwustu = ceny < 200
ponizej_dwustu_nazwy = np.array(nazwy)[ponizej_dwustu]
ponizej_dwustu_ilosc = (ilosci_magazyn)[ponizej_dwustu]
print(f"Produkty poniżej 200 złotych to: {ponizej_dwustu_nazwy} ich ilość w magazynie to kolejno: {ponizej_dwustu_ilosc} ")

Produkty z oceną 4.5 to ['Laptop' 'Smartfon' 'Słuchawki' 'Monitor'] a ich ceny to kolejno: [3499 2499  349 1499]
Produkty poniżej 200 złotych to: ['Ładowarka' 'Mysz'] ich ilość w magazynie to kolejno: [312 201] 


In [132]:
#Zad 5
nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Ładowarka',
'Klawiatura', 'Mysz', 'Monitor', 'Kamera', 'Drukarka']
ceny = np.array([3499, 1899, 2499, 349, 89, 249, 129, 1499, 599, 899])
ilosci_magazyn = np.array([15, 42, 78, 156, 312, 89, 201, 23, 45, 34])
oceny_klientow = np.array([4.7, 4.2, 4.5, 4.8, 3.9, 4.1, 4.3, 4.6, 3.8, 3.5])
wartosci = ceny * ilosci_magazyn
maska_niski_stan = ilosci_magazyn < 30
nazwy_niski_stan = np.array(nazwy)[maska_niski_stan]
wartosc_niskiego_stanu = np.sum(wartosci[maska_niski_stan])
calkowita_wartosc = np.sum(wartosci)
procent_wartosci = (wartosc_niskiego_stanu / calkowita_wartosc) * 100
print(f"Produkty z niskim stanem: {nazwy_niski_stan}")
print(f"Ich łączna wartość: {wartosc_niskiego_stanu:.2f} zł")
print(f"Stanowią one {procent_wartosci:.2f}% wartości całego magazynu")

Produkty z niskim stanem: ['Laptop' 'Monitor']
Ich łączna wartość: 86962.00 zł
Stanowią one 15.83% wartości całego magazynu


In [134]:
import time
# Przygotowanie danych
rozmiar = 1_000_000
lista = list(range(rozmiar))
tablica = np.array(lista)
# Test 1: Pomnóż przez 2
start = time.perf_counter()
wynik_lista = [x * 2 for x in lista]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
wynik_numpy = tablica * 2
czas_numpy = time.perf_counter() - start
print(f"=== Mnożenie ×2 ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")
# Test 2: Suma
start = time.perf_counter()
suma_lista = sum(lista)
czas_lista = time.perf_counter() - start
start = time.perf_counter()
suma_numpy = tablica.sum()
czas_numpy = time.perf_counter() - start
print(f"\n=== Suma ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")
# Test 3: Filtrowanie (elementy > 500000)
start = time.perf_counter()
filtr_lista = [x for x in lista if x > 500000]
czas_lista = time.perf_counter() - start
start = time.perf_counter()
filtr_numpy = tablica[tablica > 500000]
czas_numpy = time.perf_counter() - start
print(f"\n=== Filtrowanie > 500k ({rozmiar:,} elementów) ===")
print(f"Lista: {czas_lista*1000:.1f} ms")
print(f"NumPy: {czas_numpy*1000:.1f} ms")
print(f"NumPy jest {czas_lista/czas_numpy:.0f}× szybszy!")

=== Mnożenie ×2 (1,000,000 elementów) ===
Lista: 54.0 ms
NumPy: 2.4 ms
NumPy jest 23× szybszy!

=== Suma (1,000,000 elementów) ===
Lista: 3.7 ms
NumPy: 0.6 ms
NumPy jest 6× szybszy!

=== Filtrowanie > 500k (1,000,000 elementów) ===
Lista: 36.3 ms
NumPy: 2.0 ms
NumPy jest 18× szybszy!


## Wnioski z benchmarku
- NumPy jest **23×** szybszy w mnożeniu
- NumPy jest **6×** szybszy w sumowaniu
- NumPy jest **18×** szybszy w filtrowaniu
- Wniosek: przy dużych danych **zawsze** używaj NumPy zamiast list